export default {
    listRekapHarIRIS: state => state.listRekapHarIRIS,
    listDataMonitMasterIris: state => state.listDataMonitMasterIris,
    listDataMonitGabIris: state => state.listDataMonitGabIris,
    listDataPerfileGabIris: state => state.listDataPerfileGabIris,
    rekapBelumProsesIris: state => state.rekapBelumProsesIris,
    rekapBelumProsesIrisDT: state => state.rekapBelumProsesIrisDT,
    listDataHareis: state => state.listDataHareis,
    sudahHareis: state => state.sudahHareis,
    belumHareis: state => state.belumHareis,
    sudahHareisDT: state => state.sudahHareisDT,
    belumHareisDT: state => state.belumHareisDT,
    tokoAktif: state => state.tokoAktif,
    tokoTS: state => state.tokoTS,
    tokoLR: state => state.tokoLR,
    listLR: state => state.listLR,
    listTS: state => state.listTS,
    loadinghareis: state => state.loadinghareis,
    listCabangHareis: state => state.listCabangHareis,
};
