export default { 
    listCekMtc: state => state.listCekMtc,    
    listCekMtc_mtrandetail: state => state.listCekMtc_mtrandetail,
    listCekMtc_mtran_iris: state => state.listCekMtc_mtran_iris,
    listCekMtc_mtran_toko:  state => state.listCekMtc_mtran_toko,
    listCekMtc_mstran_iris: state => state.listCekMtc_mstran_iris,
    listCekMtc_mstran_toko:  state => state.listCekMtc_mstran_toko, 
    listCekMtc_docno_mtran:  state => state.listCekMtc_docno_mtran, 
    listCekMtc_docno_mstran:  state => state.listCekMtc_docno_mstran, 
    listCekMtc_listrik:  state => state.listCekMtc_listrik, 
    listCekMtc_paymentpoint:  state => state.listCekMtc_paymentpoint, 
    listCekMtc_spdmast:  state => state.listCekMtc_spdmast, 
    listCekMtc_const:  state => state.listCekMtc_const, 
    listCekMtc_plastik:  state => state.listCekMtc_plastik,
    listCekMtcToko: state => state.listCekMtcToko,
    listCekMtcCabang : state => state.listCekMtcCabang,
    listCekMtc_const2 : state => state.listCekMtc_const2,
};
